-- Generated baseline: run `npx prisma migrate deploy` to create the production schema.
CREATE TYPE "AdminRole" AS ENUM ('super_admin','editor','sales');
CREATE TYPE "InquiryStatus" AS ENUM ('new','contacted','qualified','proposal_sent','won','lost','archived');
CREATE TYPE "BookingStatus" AS ENUM ('requested','confirmed','completed','cancelled');
CREATE TYPE "SubscriberStatus" AS ENUM ('active','unsubscribed');
CREATE TYPE "ContentStatus" AS ENUM ('draft','published','archived');
CREATE TABLE "AdminUser" ("id" TEXT PRIMARY KEY,"fullName" TEXT NOT NULL,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"role" "AdminRole" NOT NULL DEFAULT 'editor',"lastLoginAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ContactInquiry" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"workEmail" TEXT NOT NULL,"companyName" TEXT NOT NULL,"phoneNumber" TEXT,"projectType" TEXT NOT NULL,"budgetRange" TEXT,"message" TEXT NOT NULL,"sourcePage" TEXT NOT NULL,"status" "InquiryStatus" NOT NULL DEFAULT 'new',"assignedToId" TEXT,"notes" TEXT,"utm" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ContactInquiry_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "AdminUser"("id") ON DELETE SET NULL);
CREATE TABLE "StrategyCallBooking" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"companyName" TEXT NOT NULL,"phoneNumber" TEXT,"preferredDate" TIMESTAMP(3) NOT NULL,"preferredTime" TEXT NOT NULL,"timezone" TEXT NOT NULL,"projectSummary" TEXT NOT NULL,"status" "BookingStatus" NOT NULL DEFAULT 'requested',"calendarEventId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "NewsletterSubscriber" ("id" TEXT PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"firstName" TEXT,"status" "SubscriberStatus" NOT NULL DEFAULT 'active',"consentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"unsubscribeToken" TEXT NOT NULL UNIQUE,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "BlogPost" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"slug" TEXT NOT NULL UNIQUE,"excerpt" TEXT NOT NULL,"content" TEXT NOT NULL,"coverImageUrl" TEXT,"authorId" TEXT NOT NULL,"category" TEXT NOT NULL,"tags" TEXT[] NOT NULL,"seoTitle" TEXT,"seoDescription" TEXT,"publishedAt" TIMESTAMP(3),"status" "ContentStatus" NOT NULL DEFAULT 'draft',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BlogPost_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "AdminUser"("id") ON DELETE RESTRICT);
CREATE TABLE "CaseStudy" ("id" TEXT PRIMARY KEY,"title" TEXT NOT NULL,"slug" TEXT NOT NULL UNIQUE,"clientName" TEXT,"industry" TEXT NOT NULL,"challenge" TEXT NOT NULL,"solution" TEXT NOT NULL,"outcomes" TEXT NOT NULL,"coverImageUrl" TEXT,"galleryImages" TEXT[] NOT NULL,"seoTitle" TEXT,"seoDescription" TEXT,"publishedAt" TIMESTAMP(3),"status" "ContentStatus" NOT NULL DEFAULT 'draft',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SiteSettings" ("id" INTEGER PRIMARY KEY,"companyName" TEXT NOT NULL,"logoUrl" TEXT,"primaryEmail" TEXT NOT NULL,"phoneNumber" TEXT,"address" TEXT,"socialLinks" JSONB NOT NULL DEFAULT '{}',"consultationCTA" TEXT,"analyticsId" TEXT,"metaDefaults" JSONB NOT NULL DEFAULT '{}',"notificationEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"actorId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT,"entityId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "AdminUser"("id") ON DELETE SET NULL);
